server:
  port: 81

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: wall,stat
      aop-patterns: com.example.springboot.*
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        exclusions:
        url-pattern: /*


  jdbc:
    template:
      query-timeout: 3

#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:com/example/springbootwebadmin/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath:com/example/springbootwebadmin/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: '*' #以web方式暴露所有